version: '2'
services:

    mosquitto:
      restart: always
      hostname: mosquitto
      image: webcenter/activemq
      ports:
        - "1883:1883"
        - "8881:8881"

    mongo:
      restart: always
      hostname: mongo
      image: mongo:3.2
      command: --storageEngine wiredTiger --journal --slowms=1
      ports:
        - "27017:27017"
      volumes:
        - ./volume/mongo:/data/db
        - ./scripts:/scripts

    mysql:
      restart: always
      hostname: mysql
      image: mysql:5.7
      command:
        - --lower_case_table_names=1
      ports:
        - "3306:3306"
      environment:
        MYSQL_DATABASE: riot_main
        MYSQL_ROOT_PASSWORD: control123!
      volumes:
        - ./volume/mysql:/var/lib/mysql

    zookeeper:
      image: zookeeper:3.4.9
      ports:
        - 2181:2181
      volumes:
        - ./volume/zookeeper/data:/data
        - ./volume/zookeeper/datalog:/datalog

    kafka:
      image: mojix/vizix-docker-kafka:develop
      ports:
        - 9092:9092
      environment:
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://$KAFKA_ADDRESS:9092
        KAFKA_DELETE_TOPIC_ENABLE: "true"
        KAFKA_ZOOKEEPER_CONNECT: $ZOOKEEPER_ADDRESS:2181
        KAFKA_LOG_CLEANER_ENABLE: "true"
        KAFKA_LOG_RETENTION_HOURS: 1
      volumes:
        - ./volume/kafka/logs:/app/kafka/logs
        - ./scripts:/scripts

    services:
      restart: always
      hostname: services
      image: ${VIZIX_SERVICES_IMAGE}
      ports:
        - "8080:8080"
        - "5701:5701"
      environment:
        #MEM_XMS: ${MIN_MEMORY}
        #MEM_XMX: ${MAX_MEMORY}
        VIZIX_MONGO_PRIMARY: mongo:27017
        VIZIX_MQTT_HOST: mosquitto
        VIZIX_MYSQL_HOST: mysql
        VIZIX_MYSQL_PASSWORD: control123!
        VIZIX_HAZELCAST_DISTRIBUTED_ENABLE: "false"
        VIZIX_KAFKA_ENABLED: "true"
        VIZIX_KAFKA_ZOOKEEPER: $ZOOKEEPER_ADDRESS:2181
        VIZIX_KAFKA_SERVERS: $KAFKA_ADDRESS:9092

    ui:
      restart: always
      hostname: ui
      image: ${VIZIX_UI_IMAGE}
      ports:
        - "80:80"
      environment:
        VIZIX_API_HOST: localhost:8080

    alebridge:
      restart: always
      image: ${VIZIX_BRIDGES_IMAGE}
      hostname: alebridge
      ports:
        - "9090:9090"
      environment:
        VIZIX_BRIDGE_TYPE: alebridgemt 
        VIZIX_API_HOST: services
        VIZIX_ALEB_CODE: PNLAleBridge
        VIZIX_ALEB_PORT: 9090
        VIZIX_API_KEY: ${API_KEY}
        VIZIX_ALEB_OUTPUTTOPIC: ___v1___data1
        VIZIX_ALEB_THERADS: 10

    thingjoiner:
      hostname: thingjoiner
      image: ${VIZIX_BRIDGES_IMAGE}
      environment:
        VIZIX_BRIDGE_TYPE: thingjoiner 
        VIZIX_API_HOST: services
        VIZIX_API_KEY: ${API_KEY}
        VIZIX_CORE_CODE: ThingJoiner
      volumes:
        - ./volume/ThingJoinerStore:/var/ThingJoiner/store

    rulesprocessor:
      hostname: rulesprocessor
      image: ${VIZIX_BRIDGES_IMAGE}
      environment:
        VIZIX_BRIDGE_TYPE: kafkacorebridge
        VIZIX_API_HOST: services
        VIZIX_CORE_CODE: RulesProcessor
        VIZIX_API_KEY: ${API_KEY}
      volumes:
        - ./volume/RulesProcessorStore:/var/CEPProcessor/store

    mongoinjector:
      hostname: mongoinjector
      image: ${VIZIX_BRIDGES_IMAGE}
      environment:
        VIZIX_BRIDGE_TYPE: mongoingestor
        VIZIX_API_HOST: services
        VIZIX_API_KEY : ${API_KEY}
        VIZIX_CORE_CODE: MongoInjector
      volumes:
        - ./volume/MongoInjectorStore:/var/MongoInjector/store

    console-bridges:
      image: ${VIZIX_BRIDGES_IMAGE}
      entrypoint: 
         - /bin/sh
      hostname: console
      stdin_open: true
      tty: true

    # mqttkafkabridge:
    #   image: mojix/riot-core-bridges:feature_kafkastreams
    #   environment:
    #     VIZIX_BRIDGE_TYPE: mqttkafkabridge 
    #     VIZIX_MQTTKAFKABRIDGE_INPUTTOPICS: /v1/data/ALEBPRVSID/item
    #     VIZIX_MQTTKAFKABRIDGE_OUTPUTTOPIC: ___v1___data1
    #     VIZIX_KAFKA_CONNECTION_CODE: KAFKA
    #     VIZIX_MQTTKAFKABRIDGE_MQTTCONNECTIONCODE: MQTT
    #     VIZIX_HTTP_HOST: 10.100.0.118
    #     VIZIX_HTTP_PORT: 8080
    #     VIZIX_CONTEXT_PATH: /riot-core-services
    #     VIZIX_API_HOST: 10.100.0.118
    #     VIZIX_API_KEY: 319DCD54
    #     VIZIX_MQTTKAFKABRIDGE_CLIENTID: mqttKafkaClientId
