version: '2'
services:

    mosquitto:
      restart: always
      hostname: mosquitto
      image: webcenter/activemq
      ports:
        - "1883:1883"
        - "8881:8881"

    mongo:
      restart: always
      hostname: mongo
      image: mongo:3.2
      command: --storageEngine wiredTiger --journal --slowms=1
      ports:
        - "27017:27017"
      volumes:
        - ./mongo:/data/db

    mysql:
      restart: always
      hostname: mysql
      image: mysql:5.7
      command:
        - --lower_case_table_names=1
      ports:
        - "3306:3306"
      environment:
        MYSQL_DATABASE: riot_main
        MYSQL_ROOT_PASSWORD: control123!
      volumes:
        - ./mysql:/var/lib/mysql

    zookeeper:
      image: zookeeper:3.4.9
      ports:
        - 2181:2181
      volumes:
        - ./zookeeper/data:/data
        - ./zookeeper/datalog:/datalog

    kafka:
      image: mojix/vizix-docker-kafka:develop
      ports:
        - 9092:9092
      environment:
        # KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://10.100.0.118:9092
        KAFKA_DELETE_TOPIC_ENABLE: "true"
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_LOG_CLEANER_ENABLE: "true"
        KAFKA_LOG_RETENTION_HOURS: 1
      volumes:
        - ./kafka/logs:/app/kafka/logs
        - ./scripts:/scripts

    services:
      restart: always
      hostname: services
      image: mojix/riot-core-services:feature_kafkastreams
      ports:
        - "8080:8080"
        - "5701:5701"
      environment:
        #MEM_XMS: ${MIN_MEMORY}
        #MEM_XMX: ${MAX_MEMORY}
        VIZIX_MONGO_PRIMARY: mongo:27017
        VIZIX_MQTT_HOST: mosquitto
        VIZIX_MYSQL_HOST: mysql
        VIZIX_MYSQL_PASSWORD: control123!
        VIZIX_HAZELCAST_DISTRIBUTED_ENABLE: "false"
        VIZIX_KAFKA_ENABLED: "false"

    ui:
      restart: always
      hostname: ui
      image: mojix/riot-core-ui:feature_kafkastreams
      ports:
        - "80:80"
      environment:
        VIZIX_API_HOST: localhost:8080

    alebridge:
      restart: always
      depends_on:
        - services
        - mosquitto
        - mongo
        - mysql
      image: mojix/riot-core-bridges:feature_kafkastreams
      ports:
        - "9090:9090"
      environment:
        VIZIX_BRIDGE_TYPE: alebridgemt 
        VIZIX_API_HOST: services
        VIZIX_ALEB_CODE: ALEB
        VIZIX_ALEB_PORT: 9090
        VIZIX_API_KEY: 7B4BCCDC
        VIZIX_ALEB_OUTPUTTOPIC: ___v1___data1
        VIZIX_ALEB_THERADS: 10

    thingjoiner:
      image: mojix/riot-core-bridges:feature_kafkastreams
      environment:
        VIZIX_BRIDGE_TYPE: thingjoiner 
        VIZIX_API_HOST: services
        VIZIX_API_KEY: 7B4BCCDC
        VIZIX_CORE_CODE: ThingJoiner

    kafkacepprocessor:
      image: mojix/riot-core-bridges:feature_kafkastreams
      environment:
        VIZIX_BRIDGE_TYPE: kafkacorebridge
        VIZIX_API_HOST: services
        VIZIX_CORE_CODE: CEPProcessor
        VIZIX_API_KEY: 7B4BCCDC

    mongoDAO:
      image: mojix/riot-core-bridges:feature_kafkastreams
      environment:
        VIZIX_BRIDGE_TYPE: mongoingestor
        VIZIX_API_HOST: services
        VIZIX_API_KEY : 7B4BCCDC
        VIZIX_CORE_CODE: MongoInjector


    console:
      image: mojix/riot-core-bridges:feature_kafkastreams
      entrypoint: 
         - /bin/sh
      stdin_open: true
      tty: true

    # mqttkafkabridge:
    #   image: mojix/riot-core-bridges:feature_kafkastreams
    #   environment:
    #     VIZIX_BRIDGE_TYPE: mqttkafkabridge 
    #     VIZIX_MQTTKAFKABRIDGE_INPUTTOPICS: /v1/data/ALEBPRVSID/item
    #     VIZIX_MQTTKAFKABRIDGE_OUTPUTTOPIC: ___v1___data1
    #     VIZIX_KAFKA_CONNECTION_CODE: KAFKA
    #     VIZIX_MQTTKAFKABRIDGE_MQTTCONNECTIONCODE: MQTT
    #     VIZIX_HTTP_HOST: 10.100.0.118
    #     VIZIX_HTTP_PORT: 8080
    #     VIZIX_CONTEXT_PATH: /riot-core-services
    #     VIZIX_API_HOST: 10.100.0.118
    #     VIZIX_API_KEY: 319DCD54
    #     VIZIX_MQTTKAFKABRIDGE_CLIENTID: mqttKafkaClientId
